-- MySQL Script generated by MySQL Workbench
-- Thu Nov 19 00:50:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `Courses_20`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Courses_20` (
  `semester` VARCHAR(30) NULL,
  `course_number` VARCHAR(60) NULL,
  `course_title` VARCHAR(150) NULL,
  `instructor` VARCHAR(150) NULL,
  `meeting_times` VARCHAR(45) NULL,
  `class_type` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `cancellation_status` VARCHAR(45) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
